openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: scripts-controller
    description: Scripts Controller
paths:
  /rest/status/executeScript:
    post:
      tags:
        - scripts-controller
      summary: executeScript
      operationId: executeScript
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScriptExecutionResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/rest/status/getScripts/{projectId}/{environmentId}':
    get:
      tags:
        - scripts-controller
      summary: getScripts
      operationId: getScripts
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          style: simple
          schema:
            type: string
        - name: environmentId
          in: path
          description: environmentId
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Script:
      title: Script
      type: object
      properties:
        command:
          type: string
        name:
          type: string
        parameters:
          type: object
          additionalProperties:
            type: object
        quickExecute:
          type: boolean
        recheckStatus:
          type: boolean
    ScriptExecutionResponse:
      title: ScriptExecutionResponse
      type: object
      properties:
        result:
          type: string
        script:
          $ref: '#/components/schemas/Script'
        status:
          type: boolean
