openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: file-cache-controller
    description: File Cache Controller
paths:
  /rest/files/cache/downloadFile/**:
    get:
      tags:
        - file-cache-controller
      summary: downloadFile
      operationId: downloadFile
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
