openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: open-shift-deployment-controller
    description: Open Shift Deployment Controller
paths:
  /rest/deployment/liveness:
    get:
      tags:
        - open-shift-deployment-controller
      summary: liveness
      operationId: liveness
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /rest/deployment/readiness:
    get:
      tags:
        - open-shift-deployment-controller
      summary: readiness
      operationId: readiness
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components: {}
