openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: file-source-controller
    description: File Source Controller
paths:
  /api/v1/atp-healthcheck/files/maxFileSize:
    get:
      tags:
        - file-source-controller
      summary: getMaxFileSize
      operationId: getMaxFileSize
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: integer
                format: int64
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/atp-healthcheck/files/parseFile:
    post:
      tags:
        - file-source-controller
      summary: parseFile
      operationId: parseFile
      parameters:
        - name: mapping
          in: query
          description: mapping
          required: true
          style: form
          schema:
            type: string
        - name: rows
          in: query
          description: rows
          required: true
          style: form
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: binary
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1/atp-healthcheck/files/{id}':
    get:
      tags:
        - file-source-controller
      summary: read
      operationId: read
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1/atp-healthcheck/files/{id}/rows':
    get:
      tags:
        - file-source-controller
      summary: readRows
      operationId: readRows
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1/atp-healthcheck/files/{id}/sheetCount':
    get:
      tags:
        - file-source-controller
      summary: getSheetCount
      operationId: getSheetCount
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components: {}
