# Which docker image should be used to deploy
DOCKER_TAG: "ghcr.io/netcracker/qubership-testing-platform-environments:test_pipeline-20250717160258"
# Switching-on of Eureka client
EI_CLEAN_JOB_ENABLED: "false"
# This option turns on or off logging in graylog
GRAYLOG_ON: "false"
ENV_EI_DB_ENABLE: "false"
# This option turns Javers on or off.
JAVERS_ENABLED: "false"
# This option turns on or off kafka enable
KAFKA_ENABLE: "false"
# URL of kafka service
KAFKA_SERVERS: ""
SERVICE_ENTITIES_MIGRATION_ENABLED: "false"
KAFKA_REPORTING_SERVERS: ""
# Keycloak enabled
KEYCLOAK_ENABLED: "false"
# Keycloak realm
KEYCLOAK_REALM: ""
# IP of db
PG_DB_ADDR: "my-postgres-postgresql"
# Spring profile for security
SPRING_PROFILES: "disable-security"
keepHookLogs: false
HELPER_IMAGE: "ghcr.io/netcracker/qubership-testing-platform-helm-hook-helper:main-20250714085543"
CONTENT_SECURITY_POLICY: "*"
pg_pass: "postgrestest"
pg_user: "postgres"