name: Environments Tests

on:
  workflow_call:
    inputs:
      service_branch:
        required: false
        type: string
      versions_file:
        description: 'Path to versions list file'
        type: string
        required: true
      pipeline_branch:
        description: 'Test pipeline branch name'
        type: string
        required: true
      runner_type:
        description: 'Runner type (self-hosted or ubuntu-latest)'
        type: string
        required: false
        default: 'ubuntu-latest'
#    secrets:
#      AWS_S3_ACCESS_KEY_ID:
#        required: true
#      AWS_S3_ACCESS_KEY_SECRET:
#        required: true

jobs:
  prepare-versions:
    runs-on: ${{inputs.runner_type}}
    outputs:
      versions: ${{steps.process-versions.outputs.versions}}
      previous_version: ${{steps.process-versions.outputs.previous_version}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: '${{inputs.service_branch}}'
          repository: 'Netcracker/qubership-testing-platform-environments'
          path: 'qubership-testing-platform-environments'
      - name: Process versions file
        id: process-versions
        run: |
          versions_str=$(cat qubership-testing-platform-environments/${{inputs.versions_file}})
          versions_json=$(echo $versions_str | jq -R -s -c 'split(" ")')
          echo "versions=$versions_json" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          previous_version=$(echo "$versions_json" | jq -r '.[-1]')
          echo "previous_version=$previous_version" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  # ---------- Current service branch ----------
  #4-Clean [LATEST_SPRINT], 5-Upgrade [LATEST_SPRINT] Diff Params
  Clean-Latest-Upgrade-Diff-Params:
    runs-on: ${{inputs.runner_type}}
    name: Clean [LATEST], Upgrade [LATEST] Diff Params
    steps:
      - name: Get current workflow branch
        id: get_branch
        run: |
      - name: Checkout pipeline
        uses: actions/checkout@v4
        with:
          ref: 'main'
          repository: 'Netcracker/qubership-test-pipelines'
          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
        #- name: Install Monitoring
        #uses: ./qubership-test-pipelines/actions/monitoring/helm_deploy_monitoring
      - name: Checkout pipeline
        uses: actions/checkout@v4
        with:
          ref: 'test_pipeline'
          repository: 'Netcracker/qubership-testing-platform-environments'
          path: 'qubership-testing-platform-environments'

      - name: Clean Install Environments [LATEST]
        uses: ./qubership-testing-platform-environments/actions/env/helm_deploy_consul
        with:
          path_to_template: './qubership-testing-platform-environments/deployments/charts/atp-environments/values.yaml'
          service_branch: 'test_pipeline'
          service_name: 'atp-environments'
          repository_name: 'qubership-testing-platform-environments'
          path_to_chart: 'deployments/charts/atp-environments'
          namespace: 'atp-environments'
          helm_charts_release_config: './github/helm-charts-release-config.yaml'

      - name: Verify Environments installation
        uses: ./qubership-testing-platform-environments/actions/env/verify_installation_consul