name: Environments Tests

on:
  workflow_call:
    inputs:
      service_branch:
        required: false
        type: string
      versions_file:
        description: 'Path to versions list file'
        type: string
        required: true
      pipeline_branch:
        description: 'Test pipeline branch name'
        type: string
        required: true
      runner_type:
        description: 'Runner type (self-hosted or ubuntu-latest)'
        type: string
        required: false
        default: 'ubuntu-latest'
#    secrets:
#      AWS_S3_ACCESS_KEY_ID:
#        required: true
#      AWS_S3_ACCESS_KEY_SECRET:
#        required: true

jobs:
  Clean_Install_Environments:
    runs-on: ${{inputs.runner_type}}
    name: Clean Install Environments
    steps:
      - name: Get current workflow branch
        id: get_branch
        run: |
      - name: Checkout pipeline
        uses: actions/checkout@v4
        with:
          ref: 'main'
          repository: 'Netcracker/qubership-test-pipelines'
          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
        #- name: Install Monitoring
        #uses: ./qubership-test-pipelines/actions/monitoring/helm_deploy_monitoring
      - name: Checkout pipeline
        uses: actions/checkout@v4
        with:
          ref: 'test_pipeline'
          repository: 'Netcracker/qubership-testing-platform-environments'
          path: 'qubership-testing-platform-environments'

#      - name: Checkout folder
#        run: |
#          cd qubership-testing-platform-environments
#          ls -la

      - name: Clean Install Environments
        uses: ./qubership-testing-platform-environments/.github/actions/shared/helm_deploy
        with:
          path_to_template: './qubership-testing-platform-environments/deployments/charts/atp-environments/values.yaml'
          service_branch: 'test_pipeline'
          service_name: 'atp-environments'
          repository_name: 'qubership-testing-platform-environments'
          path_to_chart: 'deployments/charts/atp-environments'
          namespace: 'env'
          helm_charts_release_config: './github/helm-charts-release-config.yaml'

      - name: Verify Environments installation
        uses: ./qubership-testing-platform-environments/.github/actions/shared/verify_installation
        with:
          namespace: 'env'
          max_attempts: 40
          timeout: '45s'
          max_attempts_for_provisioner: 40
          timeout_for_provisioner: '10s'
          service_branch: 'test_pipeline'